persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
listener 1883

# Bridge to UXP Mosquitto
connection master
address host.docker.internal:2883

# Edge -> Master (out)
topic uhn/+/catalog out 0
topic uhn/+/adapters out 0
topic uhn/+/device/+/state out 0
topic uhn/+/device/+/pin/+ out 0
topic uhn/+/device/+/availability out 0
topic uhn/+/device/+/action/+ out 0
topic uhn/+/resource/state/+ out 0
topic uhn/+/mute/event out 0
topic uhn/+/runtime/rules out 0
topic uhn/+/runtime/status out 0
topic uhn/+/blueprint/activated out 0
topic uhn/+/system/config out 0

# Master -> Edge (in) TODO: restrict further use the edge name need to setup the prod composer for this
topic uhn/+/cmd in 0
topic uhn/+/device/+/cmd in 0
topic uhn/+/resource/cmd/+ in 0
topic uhn/+/mute/cmd in 0
topic uhn/master/blueprint/activated in 0

topic uhn/+/status both 0
topic uhn/+/identity both 0
topic uhn/+/resource/signal/+ both 0

# Allow anonymous for local dev
allow_anonymous true
