root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/mb-sim ./cmd/tools/mb-sim"
bin = "tmp/mb-sim"

include_ext = ["go","json"]
include_dir = ["cmd/tools/mb-sim", "internal/simulator", "internal/config","config"]
exclude_dir = ["tmp", "vendor"]
pre_cmd = ["jq --arg port \"$SIM_PORT\" '.buses[0].port = $port' $SIM_BASE_CONFIG > $SIM_CONFIG_PATH"]
