FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# build edge
WORKDIR /app/cmd/server/edge
RUN go build -o /edge

# build rtu simulator
WORKDIR /app/cmd/tools/rtu-sim
RUN go build -o /rtu-sim

WORKDIR /app/cmd/tools/monitor
RUN go build -o /monitor


FROM alpine:3.20
RUN apk add --no-cache socat jq
ENV EDGE_CONFIG_PATH=/config/edge-config.json \
    MQTT_URL=tcp://mosquitto:1883 \
    EDGE_NAME=edge1
COPY --from=build /edge /edge
COPY --from=build /rtu-sim /rtu-sim
COPY --from=build /monitor /monitor
COPY --from=build /app/config/edge-config-dev.json /config/edge-config-dev.json
COPY cmd/server/edge/dev-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
