FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# build edge
WORKDIR /app/cmd/server/edge
RUN go build -o /edge

# build modbus simulator (RTU + TCP in one binary)
WORKDIR /app/cmd/tools/mb-sim
RUN go build -o /mb-sim

WORKDIR /app/cmd/tools/monitor
RUN go build -o /monitor

WORKDIR /app/cmd/tools/uhnctl
RUN go build -o /uhnctl


FROM alpine:3.20
RUN apk add --no-cache socat jq
ENV UHN_EDGE_CONFIG_PATH=/config/edge-config.json \
    UHN_MQTT_URL=tcp://mosquitto:1883 \
    UHN_EDGE_NAME=edge1
COPY --from=build /edge /edge
COPY --from=build /mb-sim /mb-sim
COPY --from=build /monitor /monitor
COPY --from=build /uhnctl /uhnctl
COPY --from=build /app/config/edge-config-dev.json /config/edge-config-dev.json
COPY cmd/server/edge/dev-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
